# ワークフローの名前
name: Deploy to Xserver

# ワークフローが実行されるタイミング
on:
  push:
    branches:
      - main

# 実行されるジョブを定義
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 【改善点①】まずリポジトリのコードをチェックアウトする
      - name: Checkout repository
        uses: actions/checkout@v4

      # 【改善点②】アクションのバージョンを固定する
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0 # ← @masterからバージョン指定に変更
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}

          # 【改善点③】より堅牢なスクリプト
          script: |
            set -e # エラーが発生したら、すぐにスクリプトを停止する
            cd /home/raytree/i-iide.com/public_html/apps/qrcode_generator
            git pull origin main
            echo "✅ Deploy successful!" # 成功メッセージを表示